dryRun: true

extraArgs: {}

conditions: {}

replicaCount: 1

image:
  repository: dfroberg/draino
  tag: 5d5330c
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Add these annotations to all pods
podAnnotations: {}
  # name: value
  # prometheus.io/scrape: 'true'
  # prometheus.io/port: '9102'

# Add these labels to all pods
podLabels: {}
  # name: value

rbac:
  create: true
  serviceAccountName:

nodeSelector: {}

tolerations: []

affinity: {}

# Security Context policies for pods
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  fsGroup: 101
  runAsGroup: 101
  runAsNonRoot: true
  runAsUser: 100

containerSecurityContext:
  privileged: false
  readOnlyRootFilesystem: true
